version: '3.8'

networks:
  telemetry_net:
    driver: bridge

services:
  builder:
    image:  jonnyrembo/telemetry-system:latest
    build: .
    volumes:
      - ./:/workspace:rw 
      - ./bin:/output
    command: /usr/local/bin/build.sh
    profiles: ["build"]
    networks:
      - telemetry_net

  telemetry_server:
    image: jonnyrembo/telemetry-system:latest
    environment:
      - SOURCE_DIR=${SOURCE_DIR}
    volumes:
      - ./bin:/app:cached 
      - ./server/limits.json:/limits.json:ro
    command: 
      - /bin/sh
      - -c
      - |
        /app/telemetry_server 12345 /limits.json
    ports:
      - "12345:12345/udp"
    networks:
      - telemetry_net

  telemetry_client:
    image: jonnyrembo/telemetry-system:latest
    environment:
      - SOURCE_DIR=${SOURCE_DIR}
    volumes:
      - ./bin:/app:cached 
    networks:
      - telemetry_net
    command: ["sleep", "infinity"]
    profiles: ["test"]

  functional_tests:
    image: jonnyrembo/telemetry-system:latest
    environment:
      - SOURCE_DIR=${SOURCE_DIR}
    volumes:
      - ./bin:/app:ro
    depends_on:
      - telemetry_server
    networks:
      - telemetry_net
    command: 
      - /bin/sh
      - -c
      - |
         # Проверяем существование файлов перед выполнением
          echo "Contents of /app:"
          ls -la /app/bin/tests
          echo "Running functional tests..."
          /app/bin/tests/functional_tests

    profiles: ["test"]

