name: Telemetry System CI/CD

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jonnyrembo/telemetry-system:latest
      env:
        SOURCE_DIR: /workspace
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/workspace
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          # Создаем необходимые директории
          mkdir -p /workspace/{build,bin}
          
          # Сборка проекта
          ./build.sh
          
          # Запуск unit-тестов
          cd /workspace/build
          ctest --output-on-failure --verbose

      - name: Prepare artifacts
        run: |
          # Копируем артефакты на хост раннера
          cp -r /workspace/bin ${{ github.workspace }}/

      - name: Run functional tests
        run: |
          # Генерируем .env для Docker Compose
          echo "SOURCE_DIR=${{ github.workspace }}" > .env
          
          # Запускаем тестовую инфраструктуру
          docker compose up -d telemetry_server
          docker compose run --rm functional_tests