name: telemetry-system CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jonnyrembo/telemetry-system:v1.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        SOURCE_DIR: /workspace  # Используем /workspace
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/workspace  # Монтируем в /workspace
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          # Создаем build-директорию перед запуском
          ls -la /workspace
          ls -la 
          mkdir -p /workspace/build
          mkdir -p /workspace/bin
          ./build.sh  # Теперь скрипт будет работать

      - name: Run all unit tests
        run: |
          cd /workspace/build
          ctest --output-on-failure --verbose
      - name: Verify Docker installation
        run: |
          echo "PATH: $PATH"
          which docker || true
          docker --version || true
          which docker-compose || true
          docker-compose --version || true
          ls -la /usr/bin/docker* /usr/local/bin/docker*
      - name: Start infrastructure and run functional tests
        run: |
          ls -la 
          echo "DOCKER_USERNAME=$DOCKER_USERNAME" > .env
          echo "DOCKER_IMAGE=$DOCKER_USERNAME/telemetry-system:v1.0" >> .env
          echo "SOURCE_DIR=/github/workspace" >> .env
          
          # Используем docker compose (как плагин)
          docker compose up -d telemetry_server

          docker compose run --rm functional_tests
          TEST_EXIT_CODE=$?