name: telemetry-system CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jonnyrembo/telemetry-system:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        SOURCE_DIR: /workspace
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/workspace 
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          mkdir -p /workspace/build
          ./build.sh

      - name: Run all unit tests
        run: |
          cd /workspace/build
          ctest --output-on-failure --verbose
     

      - name: Start infrastructure and run functional tests
        run: |
          export SOURCE_DIR=${{ github.workspace }}
          docker compose up -d telemetry_server
          docker compose run --rm functional_tests 