name: telemetry-system CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jonnyrembo/telemetry-system:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        SOURCE_DIR: /workspace  # Используем /workspace
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/workspace  # Монтируем в /workspace
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          # Создаем build-директорию перед запуском
          ls -la /workspace
          mkdir -p /workspace/build
          mkdir -p /workspace/bin
          ./build.sh  # Теперь скрипт будет работать

      - name: Run all unit tests
        run: |
          cd /workspace/build
          ctest --output-on-failure --verbose
     
      - name: Start infrastructure and run functional tests
        run: |
           echo "Checking functional_tests binary:"
           ls -l ./bin/functional_tests || echo "Binary not found!"
            docker compose up -d telemetry_server
            # Передаем путь к тестовым данным через аргумент
            docker compose run --rm functional_tests