name: telemetry-system CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_version: ["1.0"]
    container:
      image: docker.io/jonnyrembo/telemetry-system:v1.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        COMMON_IMAGES_VERSION: "1.0"
        SOURCE_DIR: /workspace  # Используем /workspace
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/workspace  # Монтируем в /workspace
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          # Создаем build-директорию перед запуском
          ls -la /workspace
          ls -la 
          mkdir -p /workspace/build
          mkdir -p /workspace/bin
          ./build.sh  # Теперь скрипт будет работать

      - name: Run all unit tests
        run: |
          cd /workspace/build
          ctest --output-on-failure --verbose

      - name: Start infrastructure and run functional tests
        run: |
          ls -la 
          docker-compose --profile test up
          TEST_EXIT_CODE=$?
          
          # Останавливаем контейнеры
          docker compose down --volumes --remove-orphans
          exit $TEST_EXIT_CODE